class ConnStatusType:
	AUTH_OK = 5
	AWAITING_RESPONSE = 4
	BAD = 1
	MADE = 3
	NEEDED = 8
	OK = 0
	SETENV = 6
	SSL_STARTUP = 7
	STARTED = 2
class ExecStatusType:
	BAD_RESPONSE = 5
	COMMAND_OK = 1
	COPY_BOTH = 8
	COPY_IN = 4
	COPY_OUT = 3
	EMPTY_QUERY  = 0
	FATAL_ERROR = 7
	NONFATAL_ERROR = 6
	SINGLE_TUPLE = 9
	TUPLES_OK = 2
class PGContextVisibility:
	CONTEXT_ALWAYS = 2
	CONTEXT_ERRORS = 1
	CONTEXT_NEVER = 0
class PGPing:
	NO_ATTEMPT = 3
	NO_RESPONSE = 2
	OK = 0
	REJECT = 1
class PGTransactionStatusType:
	ACTIVE = 1
	IDLE = 0
	INERROR = 3
	INTRANS = 2
	UNKNOWN = 4
class PGVerbosity:
	DEFAULT = 1
	TERSE = 0
	VERBOSE = 2
class PostgresPollingStatusType:
	POLLING_ACTIVE = 4
	POLLING_FAILED  = 0
	POLLING_OK = 3
	POLLING_READING = 1
	POLLING_WRITING = 2
PG_COPYRES_ATTRS = 1
PG_COPYRES_EVENTS = 4
PG_COPYRES_NOTICEHOOKS = 8
PG_COPYRES_TUPLES = 2
PG_DIAG_COLUMN_NAME = 'c'
PG_DIAG_CONSTRAINT_NAME = 'n'
PG_DIAG_CONTEXT = 'W'
PG_DIAG_DATATYPE_NAME = 'd'
PG_DIAG_INTERNAL_POSITION = 'p'
PG_DIAG_INTERNAL_QUERY = 'q'
PG_DIAG_MESSAGE_DETAIL = 'D'
PG_DIAG_MESSAGE_HINT = 'H'
PG_DIAG_MESSAGE_PRIMARY = 'M'
PG_DIAG_SCHEMA_NAME = 's'
PG_DIAG_SEVERITY = 'S'
PG_DIAG_SEVERITY_NONLOCALIZED = 'V'
PG_DIAG_SOURCE_FILE = 'F'
PG_DIAG_SOURCE_FUNCTION = 'R'
PG_DIAG_SOURCE_LINE = 'L'
PG_DIAG_SQLSTATE = 'C'
PG_DIAG_STATEMENT_POSITION = 'P'
PG_DIAG_TABLE_NAME = 't'
PG_INT64_TYPE = 'long int'
